version: '2'

services:
  wireviz:
    build: .
#    ports:
#      - "8086:80"
    restart: unless-stopped
    labels:
      - "traefik.backend=wireviz"
      - "traefik.enable=true"
      - "traefik.http.routers.wekan.rule=Host(`wireviz.docker.lab`)"
      - "traefik.http.services.wekan.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
