version: '2'

services:
  wireviz:
    build: .
#    ports:
#      - "8086:80"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wireviz-http.entrypoints=http"
      - "traefik.http.routers.wireviz-http.rule=Host(`wireviz.docker.lab`)"
#      - "traefik.http.routers.wireviz-http.middlewares=wireviz-https"
      - "traefik.http.services.wireviz-http.loadbalancer.server.port=80"
      - "traefik.http.middlewares.wireviz-https.redirectscheme.scheme=https"
      - "traefik.http.routers.wireviz.entrypoints=https"
      - "traefik.http.routers.wireviz.rule=Host(`wireviz.docker.lab`)"
      - "traefik.http.routers.wireviz.tls=true"
      - "traefik.docker.network=traefik_proxy"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
